feature(api): add external logging
fivetran/terraform-provider-fivetran pull request #189
Opened 2023-08-23 13:20 UTC by fivetran-aleksandrboldyrev

https://fivetran.height.app/T-357670

2023-09-15 10:27 UTC, beevital reviewed
LGTM, but let's avoid code duplication in new resources.
We already have a huge debt with old resources/datasources to refactor..

2023-09-15 10:27 UTC, beevital commented on fivetran/resource_external_logging.go
> +	return &schema.Schema{Type: schema.TypeList, Required: true, MaxItems: 1,
It reminds me the same code from datasource =) Let's make it common?

2023-09-19 11:09 UTC, fivetran-aleksandrboldyrev commented
Merge main - it's about fixing conflicts via Github UI

2023-09-19 12:48 UTC, beevital requested changes
We have a bug in go-fivetran - one field should be boolean.

Also terraform should use DoCustom request and represent config as a map.

2023-09-19 12:48 UTC, beevital commented on fivetran/fivetran_test.go
> +	}
```suggestion
	}
	if groups.Data.NextCursor != nil {
	   cleanupExternalLogging()
	}
```

2023-09-19 12:48 UTC, beevital commented on fivetran/tests/mock/resource_external_logging_test.go
> +            "enable_ssl":     "enable_ssl",
shouldn't it be boolean?
Same for go-fivetran - it is a bug. It's won't work with real API.
```suggestion
            "enable_ssl":     true,
```

2023-09-19 12:48 UTC, beevital commented on fivetran/tests/mock/resource_external_logging_test.go
> +            "enable_ssl":     "enable_ssl",
public class SplunkLogCredentials implements ApiVerifiable {
    @ConfigField(type = FieldType.CONFIG_SECRED)
    public boolean enableSSL = true;

2023-09-19 12:48 UTC, beevital commented on fivetran/resource_external_logging.go
> +				},
```suggestion
				"enable_ssl": {
					Type:        schema.TypeBool,
					Optional:    true,
					Description: "Enable SSL",
				},
```

2023-09-19 12:48 UTC, beevital commented on fivetran/resource_external_logging.go
> +	}
```suggestion
	if v := c["enable_ssl"].(bool); v != "" {
		fivetranConfig.EnableSsl(v) // here will be a bug currently - we need to fix go-fivetran client. Or just use custom config.
		hasConfig = true
	}
```

2023-09-19 12:48 UTC, beevital commented on fivetran/resource_external_logging.go
> +
It's better to use map[string]interface{} and use DoCustom instead of Do request.

2023-09-20 10:49 UTC, fivetran-aleksandrboldyrev commented on fivetran/resource_external_logging.go
> +
Done

2023-09-21 11:47 UTC, beevital approved these changes
LGMT, have one suggestion in comment.

2023-09-21 11:47 UTC, beevital commented on fivetran/resource_external_logging.go
> +	c := config[0].(map[string]interface{})
If we will have list-field - we will have to transform it, becayse in resource data it represented as (*schema.List) or (*schema.Set)
And it won't be correctly handled - as it is a pointer.
It's better to implement method that copies fields from resource data to request map one by one, verifying field type in schema and transform value if needed.

2023-09-28 10:30 UTC, fivetran-aleksandrboldyrev commented on fivetran/resource_external_logging.go
> +	c := config[0].(map[string]interface{})
Created follow-up task for this suggestion

2023-09-28 11:29 UTC, merged