Allow Sync Frequency to be nil
fivetran/terraform-provider-fivetran pull request #353
Opened 2024-09-02 10:26 UTC by fivetran-jovanmanojlovic

2024-09-02 14:35 UTC, beevital requested changes

2024-09-02 14:35 UTC, beevital commented on fivetran/framework/resources/connector_schedule.go
> +	}
We should check `if !data.SyncFrequency.IsNull() && !data.SyncFrequency.IsUnknown() || data.SyncFrequency.ValueString() != ""`

2024-09-02 14:35 UTC, beevital commented on fivetran/framework/resources/connector_schedule.go
> +		if plan.SyncFrequency.ValueString() != "" {
Same here - we should check IsNull() and IsUnknown() as well.

2024-09-02 14:35 UTC, beevital commented on CHANGELOG.md
> +- Issue with SyncFrequency unable to be set to nil
```suggestion
- Issue with resource `fivetran_connector_schedule` when SyncFrequency is unknown.
```

We should introduce issues in change-log notes from user-understanding side. It's not clear what does this mean here, only we as a developers know that the issue caused by this fact. But from customer side it should be described in different manner.

2024-09-02 14:59 UTC, fivetran-aleksandrboldyrev commented on CHANGELOG.md
> +## [1.2.0](https://github.com/fivetran/terraform-provider-fivetran/compare/v1.2.8...v1.2.9)
```suggestion
## [1.2.9](https://github.com/fivetran/terraform-provider-fivetran/compare/v1.2.8...v1.2.9)
```

2024-09-03 08:20 UTC, fivetran-aleksandrboldyrev approved these changes
LGTM

2024-09-03 10:50 UTC, beevital approved these changes

2024-09-03 11:28 UTC, merged