fix(terraform-provider-fivetran): add missing host parameter.
fivetran/terraform-provider-fivetran pull request #6
Opened 2021-09-23 11:20 UTC by fivetran-denismutuzkin

Checked, the host is populated.  Closes [T-135508](https://fivetran.height.app/T-135508)

2021-09-29 10:35 UTC, felipeneuwald requested changes
Besides the code comments, have we tested generating a new version and running terraform on a real resource?

2021-09-29 10:35 UTC, felipeneuwald commented on CHANGELOG.md
> +- `host` missing field added to connector schema.
It would be good to specify that the field has been added to the "resource" connector.

2021-09-29 10:35 UTC, felipeneuwald commented on fivetran/resource_connector.go
> +	if v := c["host"].(string); len(v) > 0 {
Shouldn't be `if v := c["host"].(string); v != "" {`?

2021-09-30 07:14 UTC, fivetran-denismutuzkin commented on fivetran/resource_connector.go
> +	if v := c["host"].(string); len(v) > 0 {
Sure, I have checked the `v != ""` but used IDEA to commit, it seems VS code auto-saving is not working, my plan from now is to commit from VS code.

2021-09-30 10:04 UTC, fivetran-denismutuzkin commented on CHANGELOG.md
> +- `host` missing field added to connector schema.
This field was in schema before, I added a mapping to the client. Yes, I have tested it in a local environment.

2021-09-30 10:25 UTC, felipeneuwald requested changes

2021-09-30 10:25 UTC, felipeneuwald commented on CHANGELOG.md
> +## [0.1.2](https://github.com/fivetran/terraform-provider-fivetran/compare/v0.1.1...v0.1.2) - 2021-09-29
I think we just need to change the date and we're good to go. :-)

2021-09-30 10:34 UTC, fivetran-denismutuzkin commented on CHANGELOG.md
> +## [0.1.2](https://github.com/fivetran/terraform-provider-fivetran/compare/v0.1.1...v0.1.2) - 2021-09-29
updated

2021-09-30 10:44 UTC, felipeneuwald approved these changes
lgtm

2021-09-30 11:55 UTC, merged