feature(*): add custom user agent tag
fivetran/terraform-provider-fivetran pull request #7
Opened 2021-11-10 13:03 UTC by beevital

Custom User-Agent tag provided to track requests from terraform

2021-11-10 13:10 UTC, felipeneuwald requested changes

2021-11-10 13:10 UTC, felipeneuwald commented on fivetran/provider.go
> +	fivetranClient.CustomUserAgent("terraform-provider-fivetran")
Shouldn't we add the version?

2021-11-10 13:10 UTC, felipeneuwald commented on CHANGELOG.md
> +## [0.1.3](https://github.com/fivetran/terraform-provider-fivetran/compare/v0.1.2...v0.1.3) - 2021-11-10
It looks like a new feature. Shouldn't be `0.2.0`?

2021-11-10 13:16 UTC, beevital commented on CHANGELOG.md
> +## [0.1.3](https://github.com/fivetran/terraform-provider-fivetran/compare/v0.1.2...v0.1.3) - 2021-11-10
I think from the customer POV - there is no changes. We just added a tiny tweak. Nothing changed in functionality.

2021-11-10 13:19 UTC, beevital commented on CHANGELOG.md
> +## [0.1.3](https://github.com/fivetran/terraform-provider-fivetran/compare/v0.1.2...v0.1.3) - 2021-11-10
Let's define versioning policy:
 - If something was changed dramatically -> it's a new major (for example - we add new resource)
 - If existing schema changed or new schema added -> update minor version 0.1.0 -> 0.2.0
 - If there is no schema changes -> update sub-version 0.1.0 -> 0.1.1

2021-11-10 13:36 UTC, beevital commented on fivetran/provider.go
> +	fivetranClient.CustomUserAgent("terraform-provider-fivetran")
Yep, added.

2021-11-10 14:21 UTC, beevital commented on CHANGELOG.md
> +## [0.1.3](https://github.com/fivetran/terraform-provider-fivetran/compare/v0.1.2...v0.1.3) - 2021-11-10
According to semver - version updated to 0.2.0

2021-11-10 15:13 UTC, felipeneuwald requested changes

2021-11-10 15:13 UTC, felipeneuwald commented on fivetran/provider.go
> +	fivetranClient.CustomUserAgent("terraform-provider-fivetran/0.2.0")
Instead of having the version hardcoded, shouldn't we have something like
```go
version = "0.x.y"
fivetranClient.CustomUserAgent("terraform-provider-fivetran/" + version)
```
?

2021-11-11 07:50 UTC, beevital commented on fivetran/provider.go
> +	fivetranClient.CustomUserAgent("terraform-provider-fivetran/0.2.0")
Yep, done)

2021-11-11 10:54 UTC, felipeneuwald approved these changes
LGTM

2021-11-11 10:54 UTC, merged